function createfigure
%CREATEFIGURE

%  Auto-generated by MATLAB on 13-Aug-2019 11:53:13

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);

% Create matlab.graphics.animation.AnimatedLine
matlab.graphics.animation.AnimatedLine('Parent',axes1,'LineWidth',2,...
    'Color',[0 0 1]);

% Create matlab.graphics.animation.AnimatedLine
matlab.graphics.animation.AnimatedLine('Parent',axes1,'LineWidth',2,...
    'Color',[0 0 1]);

% Create matlab.graphics.animation.AnimatedLine
matlab.graphics.animation.AnimatedLine('Parent',axes1,'LineWidth',2,...
    'Color',[0 0 1]);

% Create matlab.graphics.animation.AnimatedLine
matlab.graphics.animation.AnimatedLine('Parent',axes1,'LineWidth',2,...
    'Color',[0 0 1]);

% Create ylabel
ylabel('DimensionlessConcentration(-)');

% Create xlabel
xlabel('Time(s)');

% Create title
title('Break Through Curve');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 14]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 1]);
